---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUdkzwSNsJgekKcEjo3Y3W/lgNAFkwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMTczMTAwWhcNMjQxMTE4MTczMTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALtElFSXrrwLWUS0xX7ycSdLW/GpPcqMGBtuFogV+8AZ36TqFB4MIbwlKUxSkcy/
    OE7rcMgeUGPXSRmQjM87DBHYMdTz1q2Iue1YHsiU9ImiNHmWr2C2Nehy2d09Lk3I
    8fC/Md/6TKsBr8uI8eTXIiM5+M/aAmywnR8bBLAfjrYjs0V0/RHvE9249Ws71Mh3
    m4cpfCvqOTTPCGlMl67WDuIbgZIJykpo9hyvzOwiKrAHkxYHEJB6xFHMXI6t5sJJ
    ECAiDQDiWnIm/akW843oFe2Uj7wyYG73B4RaoqmWrcxci+RwNuuj3hwoWfQK19xc
    byXRAAK1LDd58zv0nGPE0xEF9gi3IkFp0fcBwhA6E6G9+vwMP5Y93eWgQ336Fsf8
    giUwV2A+PqQVxTNfrU7CWdUkPnz5z7/LhLeIGXF2wxEYxrHG/YT+GeyVex7KgR5X
    NQtuPG2y+GrPnUNqy1h+NLT38msz91V8zAl6mjgvSt9TzAywVala11muqqlV5++K
    r7JChbvcZ3PoW+q9Wr1v0C6StQQc5tu6ZnZ8o/Z0hbIDoCbYRLFxdzpuIc35OQ8j
    KePjEh9z0G9lcfqRmhX0utAKqFT5vEaNjPl2OvoZkz4NTaFDp/pwQOgpQEsCdqyD
    rHdo2hMy3NE9JKMl9XKhgpVK3WiyKQ1Kq12VTfQDR4WrAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTZ4YQlK/JC0W3T
    5mdEqeyJmZei+jANBgkqhkiG9w0BAQ0FAAOCAgEApRkAcdtjjvYe6TuN9Y0bX1SH
    UwVOJonVCUFOpqkLjWy9rVvI/yGeZUfb+VNUTMIq9S4WxbIvPxQmFFq2rHifkZRp
    E0hDvIN2PMH+xx0dDKOpHeQdIZz05JBpWPeTgNgXLgYBtOn4NKShhFf4n+6YY8Y4
    dfRg/tbbWy1ZVePc0yeVX64j/865vKj3VaSwfiHiYYGFKsxWLhwVilrU+6tRPd0U
    WWHUnrlbDj6NnCWR871BDoS0GDwc1EYMFxzxGBo5nsuMVzG22FSRUmUmV51JDwTr
    QOzQd+3I31n35gHGWEOHI4jyqMXzXTaxpF1TYxcNI2Dnwq8XrPUjAZ9HpbP5Y7nB
    Kpjhsx7tw2mnKXzP8JGmE/T8IHToViAdDUuT7Is8kNwnOl8o3XlEjkr91KdUwlNj
    OiNN1esHr/t25PtpdSv4XsvRFlYWaW2HkUoYx3altQnN9lyfAJ7que1geRtITvVl
    cJJvME/sD1XYWMALsWKo8D0G4II7uHiYRPIdfEcMffGQ+Ujj1AqHUhnxmkarhi1+
    aJqfOFBqf21ZjfIRO7T/UJ94vyTajnn/ExxOSLq5BDVtiTiE4nmqwXb6y5VD1yRO
    23x/G3QpVilyr95irbUUVNFNJHC13L0w9EBkY8I6oKo4LcVykci9WuDV04AARUuq
    6+haxCu5QLRF38dkYuo=
    -----END CERTIFICATE-----
    
